# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TronWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TronWallet
  pod "AFNetworking" , '~>3.1.0'
  pod 'CocoaLumberjack' , '~>3.2.1'
  pod 'JSONModel' , '~>1.7.0'
  pod 'SDWebImage' , '~>4.1.0'
  #pod 'BlocksKit' 
  pod 'MBProgressHUD' , '~>1.0.0'
  pod 'TPKeyboardAvoiding' , '~>1.3.1'
  pod 'WebViewJavascriptBridge' , '~>6.0.2'
  #pod 'NJKWebViewProgress' , '~>0.2.3'
  pod 'SZTextView' , '~>1.3.0'
  pod 'Masonry' , '~>1.1.0'
  #pod 'Realm' 
  #pod 'Bugly'
  #pod 'JPush'
  #pod 'ZBarSDK'

end
